baseURL = 'https://KoyoOishi.github.io/'
title = 'Koyo Oishi'
theme = 'PaperMod'
defaultContentLanguage = 'en' # 基本は英語


[markup.goldmark.renderer]
  unsafe = true

[params]
  math = true
  ShowFullTextContent = false
  displayFullLangName = true

# --- 多言語設定 ---
[languages]
  [languages.en]
    languageName = 'English'
    title = 'Koyo Oishi'
    weight = 1

  [languages.ja]
    languageName = '日本語'
    title = '大石 皐遥'
    weight = 2